// Code generated by mockery v2.53.6. DO NOT EDIT.

package validatorx

import mock "github.com/stretchr/testify/mock"

// MockValidator is an autogenerated mock type for the Validator type
type MockValidator struct {
	mock.Mock
}

type MockValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidator) EXPECT() *MockValidator_Expecter {
	return &MockValidator_Expecter{mock: &_m.Mock}
}

// ValidateStruct provides a mock function with given fields: data
func (_m *MockValidator) ValidateStruct(data interface{}) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for ValidateStruct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockValidator_ValidateStruct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateStruct'
type MockValidator_ValidateStruct_Call struct {
	*mock.Call
}

// ValidateStruct is a helper method to define mock.On call
//   - data interface{}
func (_e *MockValidator_Expecter) ValidateStruct(data interface{}) *MockValidator_ValidateStruct_Call {
	return &MockValidator_ValidateStruct_Call{Call: _e.mock.On("ValidateStruct", data)}
}

func (_c *MockValidator_ValidateStruct_Call) Run(run func(data interface{})) *MockValidator_ValidateStruct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockValidator_ValidateStruct_Call) Return(_a0 error) *MockValidator_ValidateStruct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValidator_ValidateStruct_Call) RunAndReturn(run func(interface{}) error) *MockValidator_ValidateStruct_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockValidator creates a new instance of MockValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidator {
	mock := &MockValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
