// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/wisaitas/github.com/wisaitas/golang-structure/internal/golangstructure/domain/entity"
	gorm "gorm.io/gorm"

	gormx "github.com/wisaitas/github.com/wisaitas/golang-structure/pkg/db/gormx"

	mock "github.com/stretchr/testify/mock"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, value
func (_m *MockUserRepository) Create(ctx context.Context, value interface{}) error {
	ret := _m.Called(ctx, value)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - value interface{}
func (_e *MockUserRepository_Expecter) Create(ctx interface{}, value interface{}) *MockUserRepository_Create_Call {
	return &MockUserRepository_Create_Call{Call: _e.mock.On("Create", ctx, value)}
}

func (_c *MockUserRepository_Create_Call) Run(run func(ctx context.Context, value interface{})) *MockUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *MockUserRepository_Create_Call) Return(_a0 error) *MockUserRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Create_Call) RunAndReturn(run func(context.Context, interface{}) error) *MockUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, value
func (_m *MockUserRepository) Delete(ctx context.Context, value interface{}) error {
	ret := _m.Called(ctx, value)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - value interface{}
func (_e *MockUserRepository_Expecter) Delete(ctx interface{}, value interface{}) *MockUserRepository_Delete_Call {
	return &MockUserRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, value)}
}

func (_c *MockUserRepository_Delete_Call) Run(run func(ctx context.Context, value interface{})) *MockUserRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *MockUserRepository_Delete_Call) Return(_a0 error) *MockUserRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Delete_Call) RunAndReturn(run func(context.Context, interface{}) error) *MockUserRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function with given fields: ctx, items, pagination, condition, relations
func (_m *MockUserRepository) Find(ctx context.Context, items *[]entity.User, pagination *gormx.PaginationQuery, condition *gormx.Condition, relations *[]gormx.Relation) error {
	ret := _m.Called(ctx, items, pagination, condition, relations)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *[]entity.User, *gormx.PaginationQuery, *gormx.Condition, *[]gormx.Relation) error); ok {
		r0 = rf(ctx, items, pagination, condition, relations)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockUserRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - items *[]entity.User
//   - pagination *gormx.PaginationQuery
//   - condition *gormx.Condition
//   - relations *[]gormx.Relation
func (_e *MockUserRepository_Expecter) Find(ctx interface{}, items interface{}, pagination interface{}, condition interface{}, relations interface{}) *MockUserRepository_Find_Call {
	return &MockUserRepository_Find_Call{Call: _e.mock.On("Find", ctx, items, pagination, condition, relations)}
}

func (_c *MockUserRepository_Find_Call) Run(run func(ctx context.Context, items *[]entity.User, pagination *gormx.PaginationQuery, condition *gormx.Condition, relations *[]gormx.Relation)) *MockUserRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*[]entity.User), args[2].(*gormx.PaginationQuery), args[3].(*gormx.Condition), args[4].(*[]gormx.Relation))
	})
	return _c
}

func (_c *MockUserRepository_Find_Call) Return(_a0 error) *MockUserRepository_Find_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Find_Call) RunAndReturn(run func(context.Context, *[]entity.User, *gormx.PaginationQuery, *gormx.Condition, *[]gormx.Relation) error) *MockUserRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindOne provides a mock function with given fields: ctx, item, condition, relations
func (_m *MockUserRepository) FindOne(ctx context.Context, item *entity.User, condition *gormx.Condition, relations *[]gormx.Relation) error {
	ret := _m.Called(ctx, item, condition, relations)

	if len(ret) == 0 {
		panic("no return value specified for FindOne")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User, *gormx.Condition, *[]gormx.Relation) error); ok {
		r0 = rf(ctx, item, condition, relations)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_FindOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOne'
type MockUserRepository_FindOne_Call struct {
	*mock.Call
}

// FindOne is a helper method to define mock.On call
//   - ctx context.Context
//   - item *entity.User
//   - condition *gormx.Condition
//   - relations *[]gormx.Relation
func (_e *MockUserRepository_Expecter) FindOne(ctx interface{}, item interface{}, condition interface{}, relations interface{}) *MockUserRepository_FindOne_Call {
	return &MockUserRepository_FindOne_Call{Call: _e.mock.On("FindOne", ctx, item, condition, relations)}
}

func (_c *MockUserRepository_FindOne_Call) Run(run func(ctx context.Context, item *entity.User, condition *gormx.Condition, relations *[]gormx.Relation)) *MockUserRepository_FindOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.User), args[2].(*gormx.Condition), args[3].(*[]gormx.Relation))
	})
	return _c
}

func (_c *MockUserRepository_FindOne_Call) Return(_a0 error) *MockUserRepository_FindOne_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_FindOne_Call) RunAndReturn(run func(context.Context, *entity.User, *gormx.Condition, *[]gormx.Relation) error) *MockUserRepository_FindOne_Call {
	_c.Call.Return(run)
	return _c
}

// GetDB provides a mock function with given fields: ctx
func (_m *MockUserRepository) GetDB(ctx context.Context) *gorm.DB {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDB")
	}

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// MockUserRepository_GetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDB'
type MockUserRepository_GetDB_Call struct {
	*mock.Call
}

// GetDB is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserRepository_Expecter) GetDB(ctx interface{}) *MockUserRepository_GetDB_Call {
	return &MockUserRepository_GetDB_Call{Call: _e.mock.On("GetDB", ctx)}
}

func (_c *MockUserRepository_GetDB_Call) Run(run func(ctx context.Context)) *MockUserRepository_GetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUserRepository_GetDB_Call) Return(_a0 *gorm.DB) *MockUserRepository_GetDB_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_GetDB_Call) RunAndReturn(run func(context.Context) *gorm.DB) *MockUserRepository_GetDB_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, value
func (_m *MockUserRepository) Save(ctx context.Context, value interface{}) error {
	ret := _m.Called(ctx, value)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockUserRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - value interface{}
func (_e *MockUserRepository_Expecter) Save(ctx interface{}, value interface{}) *MockUserRepository_Save_Call {
	return &MockUserRepository_Save_Call{Call: _e.mock.On("Save", ctx, value)}
}

func (_c *MockUserRepository_Save_Call) Run(run func(ctx context.Context, value interface{})) *MockUserRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *MockUserRepository_Save_Call) Return(_a0 error) *MockUserRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Save_Call) RunAndReturn(run func(context.Context, interface{}) error) *MockUserRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Transaction provides a mock function with given fields: ctx, fn
func (_m *MockUserRepository) Transaction(ctx context.Context, fn func(gormx.BaseRepository[entity.User]) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Transaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(gormx.BaseRepository[entity.User]) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Transaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transaction'
type MockUserRepository_Transaction_Call struct {
	*mock.Call
}

// Transaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(gormx.BaseRepository[entity.User]) error
func (_e *MockUserRepository_Expecter) Transaction(ctx interface{}, fn interface{}) *MockUserRepository_Transaction_Call {
	return &MockUserRepository_Transaction_Call{Call: _e.mock.On("Transaction", ctx, fn)}
}

func (_c *MockUserRepository_Transaction_Call) Run(run func(ctx context.Context, fn func(gormx.BaseRepository[entity.User]) error)) *MockUserRepository_Transaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(gormx.BaseRepository[entity.User]) error))
	})
	return _c
}

func (_c *MockUserRepository_Transaction_Call) Return(_a0 error) *MockUserRepository_Transaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Transaction_Call) RunAndReturn(run func(context.Context, func(gormx.BaseRepository[entity.User]) error) error) *MockUserRepository_Transaction_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, value
func (_m *MockUserRepository) Update(ctx context.Context, value interface{}) error {
	ret := _m.Called(ctx, value)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - value interface{}
func (_e *MockUserRepository_Expecter) Update(ctx interface{}, value interface{}) *MockUserRepository_Update_Call {
	return &MockUserRepository_Update_Call{Call: _e.mock.On("Update", ctx, value)}
}

func (_c *MockUserRepository_Update_Call) Run(run func(ctx context.Context, value interface{})) *MockUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *MockUserRepository_Update_Call) Return(_a0 error) *MockUserRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Update_Call) RunAndReturn(run func(context.Context, interface{}) error) *MockUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function with given fields: tx
func (_m *MockUserRepository) WithTx(tx *gorm.DB) gormx.BaseRepository[entity.User] {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 gormx.BaseRepository[entity.User]
	if rf, ok := ret.Get(0).(func(*gorm.DB) gormx.BaseRepository[entity.User]); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gormx.BaseRepository[entity.User])
		}
	}

	return r0
}

// MockUserRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockUserRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockUserRepository_Expecter) WithTx(tx interface{}) *MockUserRepository_WithTx_Call {
	return &MockUserRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockUserRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockUserRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB))
	})
	return _c
}

func (_c *MockUserRepository_WithTx_Call) Return(_a0 gormx.BaseRepository[entity.User]) *MockUserRepository_WithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_WithTx_Call) RunAndReturn(run func(*gorm.DB) gormx.BaseRepository[entity.User]) *MockUserRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
