// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/wisaitas/golang-structure/internal/golangstructure/domain/entity"
	gorm "gorm.io/gorm"

	gormx "github.com/wisaitas/golang-structure/pkg/db/gormx"

	mock "github.com/stretchr/testify/mock"
)

// MockUserLogRepository is an autogenerated mock type for the UserLogRepository type
type MockUserLogRepository struct {
	mock.Mock
}

type MockUserLogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserLogRepository) EXPECT() *MockUserLogRepository_Expecter {
	return &MockUserLogRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, value
func (_m *MockUserLogRepository) Create(ctx context.Context, value interface{}) error {
	ret := _m.Called(ctx, value)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserLogRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserLogRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - value interface{}
func (_e *MockUserLogRepository_Expecter) Create(ctx interface{}, value interface{}) *MockUserLogRepository_Create_Call {
	return &MockUserLogRepository_Create_Call{Call: _e.mock.On("Create", ctx, value)}
}

func (_c *MockUserLogRepository_Create_Call) Run(run func(ctx context.Context, value interface{})) *MockUserLogRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *MockUserLogRepository_Create_Call) Return(_a0 error) *MockUserLogRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserLogRepository_Create_Call) RunAndReturn(run func(context.Context, interface{}) error) *MockUserLogRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, value
func (_m *MockUserLogRepository) Delete(ctx context.Context, value interface{}) error {
	ret := _m.Called(ctx, value)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserLogRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserLogRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - value interface{}
func (_e *MockUserLogRepository_Expecter) Delete(ctx interface{}, value interface{}) *MockUserLogRepository_Delete_Call {
	return &MockUserLogRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, value)}
}

func (_c *MockUserLogRepository_Delete_Call) Run(run func(ctx context.Context, value interface{})) *MockUserLogRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *MockUserLogRepository_Delete_Call) Return(_a0 error) *MockUserLogRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserLogRepository_Delete_Call) RunAndReturn(run func(context.Context, interface{}) error) *MockUserLogRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function with given fields: ctx, items, pagination, condition, relations
func (_m *MockUserLogRepository) Find(ctx context.Context, items *[]entity.UserLog, pagination *gormx.PaginationQuery, condition *gormx.Condition, relations *[]gormx.Relation) error {
	ret := _m.Called(ctx, items, pagination, condition, relations)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *[]entity.UserLog, *gormx.PaginationQuery, *gormx.Condition, *[]gormx.Relation) error); ok {
		r0 = rf(ctx, items, pagination, condition, relations)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserLogRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockUserLogRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - items *[]entity.UserLog
//   - pagination *gormx.PaginationQuery
//   - condition *gormx.Condition
//   - relations *[]gormx.Relation
func (_e *MockUserLogRepository_Expecter) Find(ctx interface{}, items interface{}, pagination interface{}, condition interface{}, relations interface{}) *MockUserLogRepository_Find_Call {
	return &MockUserLogRepository_Find_Call{Call: _e.mock.On("Find", ctx, items, pagination, condition, relations)}
}

func (_c *MockUserLogRepository_Find_Call) Run(run func(ctx context.Context, items *[]entity.UserLog, pagination *gormx.PaginationQuery, condition *gormx.Condition, relations *[]gormx.Relation)) *MockUserLogRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*[]entity.UserLog), args[2].(*gormx.PaginationQuery), args[3].(*gormx.Condition), args[4].(*[]gormx.Relation))
	})
	return _c
}

func (_c *MockUserLogRepository_Find_Call) Return(_a0 error) *MockUserLogRepository_Find_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserLogRepository_Find_Call) RunAndReturn(run func(context.Context, *[]entity.UserLog, *gormx.PaginationQuery, *gormx.Condition, *[]gormx.Relation) error) *MockUserLogRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindOne provides a mock function with given fields: ctx, item, condition, relations
func (_m *MockUserLogRepository) FindOne(ctx context.Context, item *entity.UserLog, condition *gormx.Condition, relations *[]gormx.Relation) error {
	ret := _m.Called(ctx, item, condition, relations)

	if len(ret) == 0 {
		panic("no return value specified for FindOne")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.UserLog, *gormx.Condition, *[]gormx.Relation) error); ok {
		r0 = rf(ctx, item, condition, relations)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserLogRepository_FindOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOne'
type MockUserLogRepository_FindOne_Call struct {
	*mock.Call
}

// FindOne is a helper method to define mock.On call
//   - ctx context.Context
//   - item *entity.UserLog
//   - condition *gormx.Condition
//   - relations *[]gormx.Relation
func (_e *MockUserLogRepository_Expecter) FindOne(ctx interface{}, item interface{}, condition interface{}, relations interface{}) *MockUserLogRepository_FindOne_Call {
	return &MockUserLogRepository_FindOne_Call{Call: _e.mock.On("FindOne", ctx, item, condition, relations)}
}

func (_c *MockUserLogRepository_FindOne_Call) Run(run func(ctx context.Context, item *entity.UserLog, condition *gormx.Condition, relations *[]gormx.Relation)) *MockUserLogRepository_FindOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.UserLog), args[2].(*gormx.Condition), args[3].(*[]gormx.Relation))
	})
	return _c
}

func (_c *MockUserLogRepository_FindOne_Call) Return(_a0 error) *MockUserLogRepository_FindOne_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserLogRepository_FindOne_Call) RunAndReturn(run func(context.Context, *entity.UserLog, *gormx.Condition, *[]gormx.Relation) error) *MockUserLogRepository_FindOne_Call {
	_c.Call.Return(run)
	return _c
}

// GetDB provides a mock function with given fields: ctx
func (_m *MockUserLogRepository) GetDB(ctx context.Context) *gorm.DB {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDB")
	}

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// MockUserLogRepository_GetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDB'
type MockUserLogRepository_GetDB_Call struct {
	*mock.Call
}

// GetDB is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserLogRepository_Expecter) GetDB(ctx interface{}) *MockUserLogRepository_GetDB_Call {
	return &MockUserLogRepository_GetDB_Call{Call: _e.mock.On("GetDB", ctx)}
}

func (_c *MockUserLogRepository_GetDB_Call) Run(run func(ctx context.Context)) *MockUserLogRepository_GetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUserLogRepository_GetDB_Call) Return(_a0 *gorm.DB) *MockUserLogRepository_GetDB_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserLogRepository_GetDB_Call) RunAndReturn(run func(context.Context) *gorm.DB) *MockUserLogRepository_GetDB_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, value
func (_m *MockUserLogRepository) Save(ctx context.Context, value interface{}) error {
	ret := _m.Called(ctx, value)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserLogRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockUserLogRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - value interface{}
func (_e *MockUserLogRepository_Expecter) Save(ctx interface{}, value interface{}) *MockUserLogRepository_Save_Call {
	return &MockUserLogRepository_Save_Call{Call: _e.mock.On("Save", ctx, value)}
}

func (_c *MockUserLogRepository_Save_Call) Run(run func(ctx context.Context, value interface{})) *MockUserLogRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *MockUserLogRepository_Save_Call) Return(_a0 error) *MockUserLogRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserLogRepository_Save_Call) RunAndReturn(run func(context.Context, interface{}) error) *MockUserLogRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Transaction provides a mock function with given fields: ctx, fn
func (_m *MockUserLogRepository) Transaction(ctx context.Context, fn func(gormx.BaseRepository[entity.UserLog]) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Transaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(gormx.BaseRepository[entity.UserLog]) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserLogRepository_Transaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transaction'
type MockUserLogRepository_Transaction_Call struct {
	*mock.Call
}

// Transaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(gormx.BaseRepository[entity.UserLog]) error
func (_e *MockUserLogRepository_Expecter) Transaction(ctx interface{}, fn interface{}) *MockUserLogRepository_Transaction_Call {
	return &MockUserLogRepository_Transaction_Call{Call: _e.mock.On("Transaction", ctx, fn)}
}

func (_c *MockUserLogRepository_Transaction_Call) Run(run func(ctx context.Context, fn func(gormx.BaseRepository[entity.UserLog]) error)) *MockUserLogRepository_Transaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(gormx.BaseRepository[entity.UserLog]) error))
	})
	return _c
}

func (_c *MockUserLogRepository_Transaction_Call) Return(_a0 error) *MockUserLogRepository_Transaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserLogRepository_Transaction_Call) RunAndReturn(run func(context.Context, func(gormx.BaseRepository[entity.UserLog]) error) error) *MockUserLogRepository_Transaction_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, value
func (_m *MockUserLogRepository) Update(ctx context.Context, value interface{}) error {
	ret := _m.Called(ctx, value)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserLogRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserLogRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - value interface{}
func (_e *MockUserLogRepository_Expecter) Update(ctx interface{}, value interface{}) *MockUserLogRepository_Update_Call {
	return &MockUserLogRepository_Update_Call{Call: _e.mock.On("Update", ctx, value)}
}

func (_c *MockUserLogRepository_Update_Call) Run(run func(ctx context.Context, value interface{})) *MockUserLogRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *MockUserLogRepository_Update_Call) Return(_a0 error) *MockUserLogRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserLogRepository_Update_Call) RunAndReturn(run func(context.Context, interface{}) error) *MockUserLogRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function with given fields: tx
func (_m *MockUserLogRepository) WithTx(tx *gorm.DB) gormx.BaseRepository[entity.UserLog] {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 gormx.BaseRepository[entity.UserLog]
	if rf, ok := ret.Get(0).(func(*gorm.DB) gormx.BaseRepository[entity.UserLog]); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gormx.BaseRepository[entity.UserLog])
		}
	}

	return r0
}

// MockUserLogRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockUserLogRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx *gorm.DB
func (_e *MockUserLogRepository_Expecter) WithTx(tx interface{}) *MockUserLogRepository_WithTx_Call {
	return &MockUserLogRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockUserLogRepository_WithTx_Call) Run(run func(tx *gorm.DB)) *MockUserLogRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB))
	})
	return _c
}

func (_c *MockUserLogRepository_WithTx_Call) Return(_a0 gormx.BaseRepository[entity.UserLog]) *MockUserLogRepository_WithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserLogRepository_WithTx_Call) RunAndReturn(run func(*gorm.DB) gormx.BaseRepository[entity.UserLog]) *MockUserLogRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserLogRepository creates a new instance of MockUserLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserLogRepository {
	mock := &MockUserLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
