// Code generated by genentity (Postgres introspection). DO NOT EDIT.


package entity


import (
	"time"
	"github.com/google/uuid"
	"gorm.io/gorm"
)


type TblUsers struct {
	ID uuid.UUID `gorm:"column:id;primaryKey;not null;default:gen_random_uuid()"`
	Name string `gorm:"column:name;not null"`
	Age int `gorm:"column:age;not null"`
	Email string `gorm:"column:email;not null"`
	Password string `gorm:"column:password;not null"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:now()"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:now()"`
	DeletedAt *gorm.DeletedAt `gorm:"column:deleted_at"`
}

func (TblUsers) TableName() string {
	return "tbl_users"
}
