// Code generated by genentity (Postgres introspection). DO NOT EDIT.


package entity


import (
	"time"
	"github.com/google/uuid"
)


type TblUserLogs struct {
	ID uuid.UUID `gorm:"column:id;primaryKey;not null;default:gen_random_uuid()"`
	UserID uuid.UUID `gorm:"column:user_id;not null"`
	Action string `gorm:"column:action;not null"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:now()"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:now()"`
}

func (TblUserLogs) TableName() string {
	return "tbl_user_logs"
}
