POST http://localhost:8081/register
Content-Type: application/json

{
    "name": "test01",
    "email": "com@gmail.com",
    "age": 1,
    "password": "12345678",
    "confirm_password": "12345678"
}