POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "name": "test01",
    "email": "test01@gmail.com",
    "age": 1,
    "password": "12345678",
    "confirm_password": "12345678"
}